In [1]:
import pandas as pd
import numpy as np
import os
import re

In [2]:
sim_type = 'clinvar'
sensitivity = ''
padding = 0
cn_values = [1, 3]

In [3]:
run_number = '29'
work_folder_extension = ''
dnascreen_run = run_number + work_folder_extension
sim_dir='/Users/zlaw0001/Library/CloudStorage/OneDrive-MonashUniversity/Joshua_PhD_Project/Aim_1/CNV_calling/simulation_hom_deletion/experiment_onsimulation_using_clinvar'
exome_depth_dir='/Users/zlaw0001/Library/CloudStorage/OneDrive-MonashUniversity/Joshua_PhD_Project/Aim_1/CNV_calling/exome_depth'

In [4]:
selected_windows_dir = sim_dir + '/run' + dnascreen_run + '/selected_regions'

In [5]:
# Load the bed file into a dataframe
exons = pd.read_csv(exome_depth_dir + '/bed_files/9genes_25bp.fix.sorted.bed', sep='\t', header=None, names=['chr', 'start', 'end', 'name', 'idk','strand'])

## Checking exons covered by selected_windows

In [6]:
# Check if the boundary of the simulated window falls within an exon for both VS and ED!

results = []

for cn in cn_values:
    selected_windows_file = selected_windows_dir + f'/selected_regions_cn{cn}_sample'
    selected_windows = pd.read_csv(selected_windows_file, sep='\t', 
                               header=None,
                               names=['sample', 'chr', 'start', 'end', 'gene'])
    
    # Doing this because we have repeated samples with different CN
    selected_windows['sample'] = 'cn' + str(cn) + '_' + selected_windows['sample'] + '.sorted'
    
    # Iterate over each row(sample) in the selected_windows dataframe
    for index, window in selected_windows.iterrows():
        # Get the chromosome, start, and end of the current window
        chr_window = window['chr']
        start_window = window['start']
        end_window = window['end']
        
        # Filter exons to find those that are on the same chromosome and within or overlap with the start and end of the current window
        exons_overlapping_window = exons[(exons['chr'] == chr_window) &
                                (exons['start'] < end_window) &
                                (exons['end'] > start_window)]
        
        # Count the number of exons that match the criteria
        count_exons_overlapping_simulated_window = len(exons_overlapping_window)

        # Filter exons to find those that are on the same chromosome and within the start and end of the current window
        exons_within_window = exons[(exons['chr'] == chr_window) &
                                (exons['start'] >= start_window) &
                                (exons['end'] <= end_window)]
        
        # Count the number of exons that match the criteria
        count_exons_within_simulated_window = len(exons_within_window)

        
        # Calculate the summed length of the exons
        summed_length_exons_overlapping = (exons_overlapping_window['end'] - exons_overlapping_window['start']).sum()
        summed_length_exons_within = (exons_within_window['end'] - exons_within_window['start']).sum()
        
        # Check if the start_window or end_window falls within any exons
        overlap_with_start = exons[(exons['chr'] == chr_window) &
                                   (exons['start'] <= start_window) &
                                   (exons['end'] >= start_window)]

        overlap_with_end = exons[(exons['chr'] == chr_window) &
                                 (exons['start'] <= end_window) &
                                 (exons['end'] >= end_window)]

        NA_dict = {'chr':'NA', 'start':'NA', 'end':'NA', 'name':'NA'}

        # Convert to list of dictionaries with required fields or 'NA' if no overlap
        overlap_with_start_dict = (overlap_with_start[['chr', 'start', 'end', 'name']]
                                   .drop_duplicates()
                                   .to_dict(orient='records')[0] if not overlap_with_start.empty else NA_dict)

        overlap_with_end_dict = (overlap_with_end[['chr', 'start', 'end', 'name']]
                                 .drop_duplicates()
                                 .to_dict(orient='records')[0] if not overlap_with_end.empty else NA_dict)
        
        # Append the result to the results list
        results.append({
            'cn': cn,
            'sample': window['sample'],
            'chr': chr_window,
            'start': start_window,
            'end': end_window,
            'gene': window['gene'],
            'count_exons_overlapping_simulated_window': count_exons_overlapping_simulated_window,
            'count_exons_within_simulated_window': count_exons_within_simulated_window,
            'summed_length_exons_overlapping': summed_length_exons_overlapping,
            'summed_length_exons_within':summed_length_exons_within,
            'overlap_with_start_chr': overlap_with_start_dict['chr'],
            'overlap_with_start_start': overlap_with_start_dict['start'],
            'overlap_with_start_end': overlap_with_start_dict['end'],
            'overlap_with_start_name': overlap_with_start_dict['name'],
            'overlap_with_end_chr': overlap_with_end_dict['chr'],
            'overlap_with_end_start': overlap_with_end_dict['start'],
            'overlap_with_end_end': overlap_with_end_dict['end'],
            'overlap_with_end_name': overlap_with_end_dict['name'],
        })

In [7]:
overlapping_exons = pd.DataFrame(results)

In [8]:
overlapping_exons.to_csv(sim_dir + '/run' + dnascreen_run + '/plot_generation/simulated_windows_info.csv')

In [9]:
overlapping_exons

,cn,sample,chr,start,end,gene,count_exons_overlapping_simulated_window,count_exons_within_simulated_window,summed_length_exons_overlapping,summed_length_exons_within,overlap_with_start_chr,overlap_with_start_start,overlap_with_start_end,overlap_with_start_name,overlap_with_end_chr,overlap_with_end_start,overlap_with_end_end,overlap_with_end_name
0,1,cn1_DNS-XTHS-0105-D03-DNS009757_S20_chr2_21001...,chr2,21001710,21035728,APOB,23,21,14149,12319,chr2,21001704,21003359,APOB_cds_0,chr2,21035558,21035733,APOB_cds_22
1,1,cn1_DNS-XTHS-0107-E04-DNS009958_S221_chr2_4740...,chr2,47403067,47483228,MSH2,16,16,3605,3605,NA,NA,NA,NA,NA,NA,NA,NA
2,1,cn1_DNS-XTHS-0106-C09-DNS009900_S163_chr2_4740...,chr2,47403067,47408555,MSH2,2,1,466,261,NA,NA,NA,NA,chr2,47408375,47408580,MSH2_cds_1
3,1,cn1_DNS-XTHS-0107-F08-DNS009991_S254_chr2_4740...,chr2,47403067,47403402,MSH2,1,0,261,0,NA,NA,NA,NA,chr2,47403166,47403427,MSH2_cds_0
4,1,cn1_DNS-XTHS-0105-E07-DNS009790_S53_chr2_47403...,chr2,47403067,47429741,MSH2,7,6,1626,1376,NA,NA,NA,NA,chr2,47429716,47429966,MSH2_cds_6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,3,cn3_DNS-XTHS-0107-G08-DNS009992_S255_chr19_111...,chr19,11116092,11116999,LDLR,2,0,359,0,chr19,11116068,11116237,LDLR_cds_10,chr19,11116833,11117023,LDLR_cds_11
622,3,cn3_DNS-XTHS-0106-H04-DNS009865_S128_chr19_111...,chr19,11120082,11129680,LDLR,5,3,952,552,chr19,11120066,11120258,LDLR_cds_12,chr19,11129487,11129695,LDLR_cds_16
623,3,cn3_DNS-XTHS-0107-E05-DNS009966_S229_chr19_111...,chr19,11120092,11129670,LDLR,5,3,952,552,chr19,11120066,11120258,LDLR_cds_12,chr19,11129487,11129695,LDLR_cds_16
624,3,cn3_DNS-XTHS-0105-A09-DNS009802_S65_chr19_1112...,chr19,11120092,11120522,LDLR,2,0,395,0,chr19,11120066,11120258,LDLR_cds_12,chr19,11120344,11120547,LDLR_cds_13
625,3,cn3_DNS-XTHS-0106-H12-DNS009929_S192_chr19_111...,chr19,11128008,11137335,LDLR,3,2,422,294,chr19,11127982,11128110,LDLR_cds_15,NA,NA,NA,NA

## Checking for number of CNVs that do not have an exon completely within the CNV coordinates.

In [10]:
print(str(len(overlapping_exons[overlapping_exons['count_exons_within_simulated_window'] == 0])) + ' CNVs that do not have an exon completely within the CNV coordinates.')

315 CNVs that do not have an exon completely within the CNV coordinates.

## Storing per sample CNV calls for varseq

In [11]:
varseq_tables_path = sim_dir + '/run' + dnascreen_run + '/plot_generation/varseq_tables' + sensitivity
    
cnvcalls_path = os.path.join(varseq_tables_path, 'all_cnv_calls_sim_clinvar.tsv')
sample_path = os.path.join(varseq_tables_path, 'Varseq_sample_sim_clinvar.tsv')

cnvcalls_df = pd.read_csv(cnvcalls_path, sep='\t')
sample_df = pd.read_csv(sample_path, sep = '\t')

cov_sim_sample_dir = os.path.join(varseq_tables_path, 'cov_samples')

/var/folders/hh/8vzwcgj52x12km60yd3vghr0213gzj/T/ipykernel_80865/633117776.py:6: DtypeWarning: Columns (31,42,43,44,54,55,66,67,78,91,102,103,114,115,126,127,138,139,150,151,152,162,163,174,187,198,199,210,223,234,235,236,246,259,270,271,282,283,294,295,296,306,307,318,319,330,331,342,343,344,354,355,366,367,378,379,390,391,402,403,414,415,426,427,428,438,439,440,450,451,462,463,474,475,476,486,499,510,511,522,523,534,535,546,547,558,559,560,570,571,582,583,594,595,606,607,618,619,630,631,642,643,654,667,678,679,680,690,703,704,714,715,726,727,738,739,750,751,762,763,774,775,786,787,798,799,810,811,822,823,834,835,846,847,848,858,859,870,871,872,882,895,896,906,907,918,919,930,931,942,943,954,955,966,979,990,991,1002,1003,1004,1014,1015,1026,1027,1038,1051,1062,1063,1074,1075,1086,1087,1098,1099,1110,1111,1112,1122,1123,1134,1159,1170,1171,1182,1195,1206,1207,1218,1231,1242,1243,1244,1254,1255,1266,1267,1278,1279,1280,1290,1291,1302,1303,1314,1315,1326,1327,1338,1339,1350,1351,1362,1363,1374,1375,1386,1387,1388,1398,1399,1410,1411,1422,1423,1424,1434,1435,1446,1447,1458,1459,1470,1471,1472,1482,1483,1494,1495,1506,1507,1518,1519,1530,1531,1542,1543,1554,1555,1566,1579,1590,1591,1602,1603,1614,1615,1626,1627,1638,1639,1650,1651,1662,1675,1686,1687,1688,1698,1699,1710,1711,1722,1723,1734,1735,1746,1747,1758,1759,1770,1783,1794,1795,1806,1807,1818,1819,1830,1831,1842,1843,1854,1855,1866,1867,1868,1878,1879,1880,1890,1891,1902,1903,1914,1915,1926,1927,1938,1939,1950,1951,1962,1963,1964,1974,1975,1976,1986,1987,1998,1999,2010,2011,2022,2023,2034,2035,2046,2047,2058,2059,2070,2071,2072,2082,2083,2094,2095,2106,2107,2118,2119,2130,2131,2142,2143,2154,2155,2166,2167,2168,2178,2179,2190,2191,2202,2203,2214,2215,2226,2227,2228,2238,2239,2250,2251,2262,2263,2274,2275,2286,2287,2298,2299,2310,2311,2322,2323,2334,2335,2346,2347,2358,2359,2360,2370,2371,2382,2395,2406,2407,2418,2419,2430,2431,2442,2443,2454,2455,2466,2467,2478,2479,2480,2490,2491,2502,2503,2514,2515,2526,2527,2538,2539,2550,2551,2562,2563,2574,2575,2586,2587,2598,2599,2610,2623,2624,2634,2635,2636,2646,2647,2658,2659,2660,2670,2671,2672,2682,2683,2694,2695,2706,2707,2718,2719,2730,2731,2742,2743,2754,2755,2756,2766,2767,2778,2779,2790,2791,2792,2802,2803,2814,2827,2838,2839,2850,2851,2852,2862,2863,2874,2875,2876,2886,2887,2898,2899,2910,2911,2922,2923,2934,2935,2946,2947,2958,2959,2970,2971,2982,2983,2994,2995,3006,3007,3018,3019,3030,3031,3042,3055,3056,3066,3067,3078,3079,3090,3091,3102,3103,3114,3115,3126,3127,3138,3139,3150,3151,3162,3163,3174,3175,3186,3187,3198,3199,3210,3211,3222,3223,3234,3235,3236,3246,3247,3248,3258,3259,3270,3271,3282,3283,3294,3295,3296,3306,3319,3330,3331,3342,3343,3354,3355,3366,3367,3378,3379,3390,3391,3402,3403,3414,3415,3426,3427,3438,3439,3440,3450,3451,3462,3463,3474,3475,3486,3487,3498,3499,3510,3511,3522,3523,3534,3535,3546,3547,3558,3559,3570,3583,3594,3595,3606,3607,3618,3619,3630,3631,3632,3642,3643,3644,3654,3655,3666,3667,3678,3679,3690,3691,3702,3703,3714,3715,3716,3726,3727,3738,3739,3750,3751,3762,3763,3774,3775,3786,3787,3798,3799,3810,3811,3822,3823,3834,3835,3836,3846,3847,3858,3859,3870,3871,3882,3883,3894,3895,3906,3907,3918,3931,3932,3942,3943,3954,3955,3966,3967,3978,3979,3990,3991,4002,4003,4014,4015,4026,4027,4038,4039,4050,4051,4062,4063,4074,4075,4086,4087,4088,4098,4099,4100,4110,4111,4112,4122,4123,4124,4134,4135,4146,4147,4158,4159,4170,4183,4194,4195,4206,4207,4208,4218,4219,4230,4231,4242,4243,4254,4255,4256,4266,4267,4268,4278,4279,4290,4291,4302,4303,4314,4315,4326,4327,4338,4339,4350,4351,4362,4363,4374,4375,4376,4386,4387,4398,4399,4410,4411,4422,4423,4434,4435,4446,4447,4458,4459,4470,4471,4482,4483,4494,4495,4506,4507,4518,4519,4530,4531,4542,4543,4554,4555,4566,4567,4578,4579,4590,4591,4592,4602,4603,4614,4615,4626,4627,4638,4639,4650,4651,4662,4663,4674,4675,4676,4686,4687,4698,4699,4700,4710,4711,4722,4723,4734,4735,4746,4747,4758,4759,4770,4771,4782,4783,4794,4795,4806,4807,4818,4831,4842,4843,4854,4855,4866,4867,4868,4878,4879,4890,4891,4902,4903,4914,4915,4926,4927,4938,4939,4950,4951,4962,4963,4974,4975,4986,4987,4998,4999,5000,5010,5011,5022,5023,5024,5034,5035,5046,5047,5058,5059,5070,5071,5082,5083,5094,5095,5106,5107,5118,5119,5130,5131,5142,5143,5154,5155,5166,5167,5178,5179,5190,5191,5202,5203,5214,5215,5216,5226,5227,5238,5239,5250,5251,5262,5263,5274,5275,5276,5286,5287,5298,5299,5310,5311,5312,5322,5323,5324,5334,5335,5346,5347,5358,5359,5370,5371,5382,5395,5406,5407,5418,5419,5430,5431,5442,5443,5454,5455,5466,5467,5468,5478,5479,5480,5490,5491,5502,5503,5514,5527,5538,5539,5550,5551,5562,5563,5574,5575,5586,5587,5598,5599,5610,5611,5622,5623,5634,5635,5636,5646,5647,5658,5659,5670,5671,5672,5682,5683,5694,5695,5706,5707,5708,5718,5719,5730,5731,5742,5743,5744,5754,5755,5766,5767,5778,5779,5790,5791,5802,5803,5814,5815,5826,5827,5838,5839,5850,5851,5862,5863,5874,5875,5886,5887,5898,5899,5910,5911,5922,5923,5934,5935,5936,5946,5947,5958,5959,5970,5971,5982,5983,5994,5995,6006,6007,6018,6019,6020,6030,6031,6042,6043,6044,6054,6067,6068,6078,6079,6090,6091,6102,6103,6114,6115,6126,6127,6138,6139,6150,6151,6162,6163,6174,6175,6186,6187,6198,6199,6210,6211,6212,6222,6223,6224,6234,6235,6246,6247,6258,6259,6260,6270,6271,6272,6282,6283,6294,6295,6306,6307,6318,6319,6330,6331,6342,6343,6354,6355,6356,6366,6367,6378,6379,6390,6391,6402,6403,6414,6415,6416,6426,6427,6438,6439,6440,6450,6451,6462,6463,6464,6474,6475,6486,6487,6488,6498,6499,6500,6510,6511,6512,6522,6523,6524,6534,6547,6548,6558,6559,6570,6571,6572,6582,6583,6594,6595,6596,6606,6607,6618,6619,6630,6631,6632,6642,6643,6644,6654,6655,6666,6679,6690,6703,6704,6714,6715,6716,6726,6727,6738,6739,6750,6751,6752,6762,6763,6774,6787,6788,6798,6799,6800,6810,6811,6812,6822,6823,6824,6834,6835,6836,6846,6871,6872,6882,6883,6894,6895,6896,6906,6919,6930,6931,6942,6943,6954,6955,6956,6966,6967,6978,6979,6990,7015,7026,7027,7028,7038,7039,7050,7051,7062,7075,7076,7086,7087,7088,7098,7111,7122,7123,7124,7134,7135,7136,7146,7147,7158,7159,7170,7171,7172,7182,7183,7194,7195,7206,7207,7218,7219,7230,7231,7242,7243,7254,7255,7256,7266,7267,7278,7279,7280,7290,7291,7302,7303,7304,7314,7315,7326,7327,7328,7338,7351,7362,7363,7374,7375,7386,7387,7398,7399,7400,7410,7411,7412,7422,7423,7424,7434,7435,7436,7446,7447,7458,7459,7460,7470,7471,7482,7483,7494,7495,7506,7507,7518,7519,7530,7531,7532,7542) have mixed types. Specify dtype option on import or set low_memory=False.
  cnvcalls_df = pd.read_csv(cnvcalls_path, sep='\t')

## The code below is a sanity check of whether samples in reference set are unique and not repeated. Also checks if the target sample is in the reference set itself.

In [12]:
# Initialize counters and lists to store row indices
duplicate_rows = []
matching_rows = []

# Process each row in sample_df
for index, row in sample_df.iterrows():
    # Get main sample ID without prefix 'cn#_' and suffix '.sorted'
    main_sample_id = re.sub(r'^(cn\d+_)?|\.sorted$', '', row['Samples'])

    # Initialize lists to hold processed reference samples
    sample_names = []

    # Split the reference samples by commas
    for item in row['Reference Samples'].split(','):
        # Extract the sample name using regex
        name_match = re.search(r'^[^\(]+', item)
        
        if name_match:
            # Clean the reference sample name by removing '.hq.sorted.marked' and '.sorted'
            ref_sample_id = re.sub(r'\.hq\.sorted\.marked|\.sorted$', '', name_match.group().strip())
            sample_names.append(ref_sample_id)

    # Check for duplicate reference samples
    if len(sample_names) != len(set(sample_names)):
        duplicate_rows.append(index)  # Store the index of the row with duplicates

    # Check if any reference sample matches the main sample ID
    if main_sample_id in sample_names:
        matching_rows.append(index)  # Store the index of the row with matches

# Print the results
if duplicate_rows:
    print(f"Number of rows with duplicate reference samples: {len(duplicate_rows)}")
    print(f"Rows with duplicates: {duplicate_rows}")
else:
    print("No rows have duplicate reference samples.")

if matching_rows:
    print(f"Number of rows with reference samples matching main sample ID: {len(matching_rows)}")
    print(f"Rows with matches: {matching_rows}")
else:
    print("No rows have reference samples matching main sample ID.")

No rows have duplicate reference samples.
No rows have reference samples matching main sample ID.

## The code below extracts CNV calls per sample.

In [13]:
real_varseq_data_dir = "/Users/zlaw0001/Library/CloudStorage/OneDrive-MonashUniversity/Joshua_PhD_Project/Aim_1/CNV_calling/VarSeq_CNV/varseq_tables_on_real_data" + "/run" + run_number
cov_real_sample_dir = real_varseq_data_dir + "/cov_samples"

In [14]:
import numpy as np
import pandas as pd
import os

# Storing average z-scores of non-matching exons for each copy number (CN)
avg_z_scores_all_nonmatching_sim_exons = [[] for _ in range(5)]

# Lists to store sample IDs, metrics for CNV calls, and metrics for coverage regions if the CNV is missed
sample_lst = []
percent_diff_lst = []
avg_nonmatching_sim_z_score_lst = []
CNV_coord_chr = []
CNV_coord_start = []
CNV_coord_end = []
region_size_lst = []
number_of_exons_varseq = []
type_lst = []
flag_lst = []
orig_target_mean_depth_lst = []
orig_z_score_lst = []
orig_ratio_lst = []
sim_target_mean_depth_lst = []
sim_z_score_lst = []
sim_ratio_lst = []
VS_target_mean_depth_lst = []
VS_z_score_lst = []
VS_ratio_lst = []
variants_considered_lst = []
supporting_LOH_variants_lst = []
estimated_CN_lst = []
GC_content_lst = []
p_val_lst = []
precision_levels_lst = []

# Iterate over each sample
for i in range(31, len(cnvcalls_df.columns), 12):
    sample_id = cnvcalls_df.columns[i][:-10]

    # Extract real sample id using re.search
    sample_id_real = re.search(r"(DNS-[A-Z0-9-]+_S[0-9]+)", sample_id).group(0)
    
    sample_cn = overlapping_exons[overlapping_exons['sample'] == sample_id]['cn'].values[0]
    percent_diff = sample_df[sample_df['Samples'] == sample_id]['Percent Difference'].values[0]
    
    # Load simulated coverage statistics
    cov_sim_sample_file = os.path.join(cov_sim_sample_dir, f'cov_sim_{sim_type} - {sample_id}.tsv')
    cov_sim_sample_df = pd.read_csv(cov_sim_sample_file, sep='\t')

    # Load original coverage statistics
    cov_real_sample_file = os.path.join(cov_real_sample_dir, f'CNV_run{run_number} - {sample_id_real}.tsv')
    cov_real_sample_df = pd.read_csv(cov_real_sample_file, sep='\t')

    # Check if there is a CNV call in VarSeq with p-value <= 0.05
    any_value_check = cnvcalls_df.iloc[0:len(cnvcalls_df), i+10].apply(
        lambda x: not pd.isnull(x) and (float(x) < 0.05)
    )

    # Define simulated CNV coordinates
    sim_chr = int(overlapping_exons.loc[overlapping_exons['sample'] == sample_id]['chr'].values[0][3:])
    sim_start = overlapping_exons.loc[overlapping_exons['sample'] == sample_id]['start'].values[0]
    sim_end = overlapping_exons.loc[overlapping_exons['sample'] == sample_id]['end'].values[0]
    # count_exons_overlapping_simulated_window = overlapping_exons.loc[overlapping_exons['sample'] == sample_id]['count_exons_overlapping_simulated_window'].values[0]

    # Extract chromosome, start, and end from the Region column
    cov_sim_sample_df[['chr', 'start', 'end']] = cov_sim_sample_df['Region'].str.extract(r'(\d+):(\d+)-(\d+)')
    cov_sim_sample_df['chr'] = cov_sim_sample_df['chr'].astype(int)
    cov_sim_sample_df['start'] = cov_sim_sample_df['start'].astype(int)
    cov_sim_sample_df['end'] = cov_sim_sample_df['end'].astype(int)

    mask = (
        (cov_sim_sample_df['chr'] == sim_chr) &
        # checking for exon intervals that overlap or are within a simulated CNV
        ((((cov_sim_sample_df['start'] <= sim_end) &
         (cov_sim_sample_df['start'] >= sim_start)) |
        ((cov_sim_sample_df['end'] <= sim_end) &
         (cov_sim_sample_df['end'] >= sim_start))) | 
         # for simulated CNVs that are smaller than an exon interval
        (((cov_sim_sample_df['start'] <= sim_end) &
         (cov_sim_sample_df['start'] <= sim_start)) &
        ((cov_sim_sample_df['end'] >= sim_end) &
         (cov_sim_sample_df['end'] >= sim_start))))
    )

    cov_real_sample_df[['chr', 'start', 'end']] = cov_real_sample_df['Region'].str.extract(r'(\d+):(\d+)-(\d+)')
    cov_real_sample_df['chr'] = cov_real_sample_df['chr'].astype(int)
    cov_real_sample_df['start'] = cov_real_sample_df['start'].astype(int)
    cov_real_sample_df['end'] = cov_real_sample_df['end'].astype(int)

    mask = (
        (cov_real_sample_df['chr'] == sim_chr) &
        # checking for exon intervals that overlap or are within a simulated CNV
        ((((cov_real_sample_df['start'] <= sim_end) &
         (cov_real_sample_df['start'] >= sim_start)) |
        ((cov_real_sample_df['end'] <= sim_end) &
         (cov_real_sample_df['end'] >= sim_start))) | 
         # for simulated CNVs that are smaller than an exon interval
        (((cov_real_sample_df['start'] <= sim_end) &
         (cov_real_sample_df['start'] <= sim_start)) &
        ((cov_real_sample_df['end'] >= sim_end) &
         (cov_real_sample_df['end'] >= sim_start))))
    )


    # Extract non-matching exons' Z-Score and calculate average Z-score
    non_matching_sim_exons = cov_sim_sample_df[~mask].drop(columns=['chr', 'start', 'end'])
    z_score_non_matching_sim_exons = non_matching_sim_exons[f'Z Score for {sample_id}'].values
    avg_nonmatching_z_score_sim = np.mean(z_score_non_matching_sim_exons)
    avg_z_scores_all_nonmatching_sim_exons[sample_cn].extend(z_score_non_matching_sim_exons)


    # Extract metrics for matching exons in the simulated data
    matching_exons_sim = cov_sim_sample_df[mask].drop(columns=['chr', 'start', 'end'])
    mean_depth_sim = np.mean(matching_exons_sim[f'{sample_id} Mean Depth'])
    z_score_sim = np.mean(matching_exons_sim[f'Z Score for {sample_id}'])
    ratio_sim = np.mean(matching_exons_sim[f'Ratio for {sample_id}'])
    variants_considered = sum(matching_exons_sim[f'Variants Considered for {sample_id}'])

    # Extract metrics for matching exons in the original data
    matching_exons_orig = cov_real_sample_df[mask].drop(columns=['chr', 'start', 'end'])
    mean_depth_orig = np.mean(matching_exons_orig[f'{sample_id_real} Mean Depth'])
    z_score_orig = np.mean(matching_exons_orig[f'Z Score for {sample_id_real}'])
    ratio_orig = np.mean(matching_exons_orig[f'Ratio for {sample_id_real}'])
    # variants_considered = sum(matching_exons_sim[f'Variants Considered for {sample_id_real}'])

    if any(any_value_check):
        for v in range(0, len(any_value_check)):
            if any_value_check.iloc[v]:

                # Append sample-specific metrics
                sample_lst.append(sample_id)
                percent_diff_lst.append(percent_diff)
                avg_nonmatching_sim_z_score_lst.append(avg_nonmatching_z_score_sim)

                # Extract chr, start, and end of VarSeq calls
                chr = 'chr' + cnvcalls_df.iloc[v, 0].split(':')[0]
                start_end = cnvcalls_df.iloc[v, 0].split(':')[1]
                start = start_end.split('-')[0]
                end = start_end.split('-')[1]
                
                CNV_coord_chr.append(chr)
                CNV_coord_start.append(start)
                CNV_coord_end.append(end)
                region_size_lst.append(cnvcalls_df.iloc[v, 4])
                number_of_exons_varseq.append(cnvcalls_df.iloc[v, 2])
                type_lst.append(cnvcalls_df.iloc[v, i])
                flag_lst.append(cnvcalls_df.iloc[v, i+1])

                # Simulated region metrics
                sim_target_mean_depth_lst.append(mean_depth_sim)
                sim_z_score_lst.append(z_score_sim)
                sim_ratio_lst.append(ratio_sim)

                # Original region metrics
                orig_target_mean_depth_lst.append(mean_depth_orig)
                orig_z_score_lst.append(z_score_orig)
                orig_ratio_lst.append(ratio_orig)

                # VarSeq metrics
                VS_target_mean_depth_lst.append(cnvcalls_df.iloc[v, i+2])
                VS_z_score_lst.append(cnvcalls_df.iloc[v, i+3])
                VS_ratio_lst.append(cnvcalls_df.iloc[v, i+4])
                variants_considered_lst.append(variants_considered)
                supporting_LOH_variants_lst.append(cnvcalls_df.iloc[v, i+7])
                estimated_CN_lst.append(cnvcalls_df.iloc[v, i+5])
                GC_content_lst.append(cnvcalls_df.iloc[v, i+9])
                p_val_lst.append(cnvcalls_df.iloc[v, i+10])
                precision_levels_lst.append(cnvcalls_df.iloc[v, i+11])
    else:
        # Append metrics if no CNV call was made
        sample_lst.append(sample_id)
        percent_diff_lst.append(percent_diff)
        avg_nonmatching_sim_z_score_lst.append(avg_nonmatching_z_score_sim)

        CNV_coord_chr.append(np.nan)
        CNV_coord_start.append(np.nan)
        CNV_coord_end.append(np.nan)
        region_size_lst.append(np.nan)
        number_of_exons_varseq.append(np.nan)
        type_lst.append(np.nan)
        flag_lst.append(np.nan)

        # Simulated region metrics
        sim_target_mean_depth_lst.append(mean_depth_sim)
        sim_z_score_lst.append(z_score_sim)
        sim_ratio_lst.append(ratio_sim)

        # Original region metrics
        orig_target_mean_depth_lst.append(mean_depth_orig)
        orig_z_score_lst.append(z_score_orig)
        orig_ratio_lst.append(ratio_orig)

        # VarSeq metrics
        VS_target_mean_depth_lst.append(np.nan)
        VS_z_score_lst.append(np.nan)
        VS_ratio_lst.append(np.nan)
        variants_considered_lst.append(variants_considered)
        supporting_LOH_variants_lst.append(np.nan)
        estimated_CN_lst.append(np.nan)
        GC_content_lst.append(np.nan)
        p_val_lst.append(np.nan)
        precision_levels_lst.append(np.nan)

In [15]:
df_sample_CNV = pd.DataFrame({'sample':sample_lst, 
                              'Percent Difference':percent_diff_lst,
                              'Avg Z-score of Non-matching Exons':avg_nonmatching_sim_z_score_lst,
                              'VS_Call_chr':CNV_coord_chr,
                              'VS_Call_start':CNV_coord_start, 
                              'VS_Call_end':CNV_coord_end, 
                              'Size of CNV': region_size_lst,
                              'Number of Exons by VarSeq call':number_of_exons_varseq,
                                'Type of CNV':type_lst,
                              'VarSeq Flags for CNV': flag_lst,
                              'Target Mean Depth of Original CNV region': orig_target_mean_depth_lst,
                             'Z-Score of Original CNV region': orig_z_score_lst,
                             'Read Ratio of Original CNV region': orig_ratio_lst,
                              'Target Mean Depth of Simulated CNV': sim_target_mean_depth_lst,
                             'Z-Score of Simulated CNV': sim_z_score_lst,
                             'Read Ratio of Simulated CNV': sim_ratio_lst,
                             'VS Target Mean Depth of CNV': VS_target_mean_depth_lst,
                             'VS Z-Score of CNV': VS_z_score_lst,
                             'VS Read Ratio of CNV': VS_ratio_lst,
                              'Variants considered in CNV': variants_considered_lst,
                              'Supporting LOH variants in CNV': supporting_LOH_variants_lst,
                             'Estimated CN of CNV': estimated_CN_lst,
                             'GC Content of CNV': GC_content_lst,
                             'p-value of CNV':p_val_lst,
                             'Precision Level of call:':precision_levels_lst}
                            )

In [16]:
# Find duplicate 'Sample' values. These are false positives since we only simulated one CNV per sample.
duplicate_samples = df_sample_CNV['sample'][df_sample_CNV['sample'].duplicated(keep=False)]

# Print or store the duplicate samples
print(duplicate_samples)

2      cn1_DNS-XTHS-0105-A02-DNS009746_S9_chr17_43045...
3      cn1_DNS-XTHS-0105-A02-DNS009746_S9_chr17_43045...
4      cn1_DNS-XTHS-0105-A02-DNS009746_S9_chr19_11100...
5      cn1_DNS-XTHS-0105-A02-DNS009746_S9_chr19_11100...
72     cn1_DNS-XTHS-0105-D02-DNS009749_S12_chr3_36993...
                             ...
656    cn3_DNS-XTHS-0107-E05-DNS009966_S229_chr19_111...
658    cn3_DNS-XTHS-0107-E11-DNS010014_S277_chr13_323...
659    cn3_DNS-XTHS-0107-E11-DNS010014_S277_chr13_323...
660    cn3_DNS-XTHS-0107-F08-DNS009991_S254_chr2_4742...
661    cn3_DNS-XTHS-0107-F08-DNS009991_S254_chr2_4742...
Name: sample, Length: 84, dtype: object

In [17]:
VarSeq_results_df  = overlapping_exons.merge(df_sample_CNV, on='sample', how='left')

In [18]:
len(np.unique(VarSeq_results_df['sample']))

626

## Calculating the overlap percentage between the CNVs called and the simulated windows.

## The percentage is calculated based on the length of the 'Called CNV', and also the 'Simulated CNV' being the denominator

In [19]:
# Outputting results of overlapping and percentage of CNV call that is within the simulated window
# we know some simulated windows have their boundaries fall within exons.
# So the CNV coordinates called won't be entirely within the simulated windows as the approach is a 
# Read-Depth based approach.

# Function to calculate overlap percentage
def calculate_within_window_percentage(start1, end1, start2, end2, denominator):
    overlap_start = max(start1, start2)
    overlap_end = min(end1, end2)
    overlap_length = max(0, overlap_end - overlap_start)
    cnvcall_length = end2 - start2
    window_length = end1 - start1
    if denominator == 'call length':
        return overlap_length / cnvcall_length if cnvcall_length > 0 else 0
    elif denominator == 'window length':
        return overlap_length / window_length if window_length > 0 else 0

# Iterate over the rows and calculate the overlap
def output_overlapping_and_within_window_percentage(row, denominator):
    # Extract chr, start, end from CNV_coordinates
    if not pd.isna(row['VS_Call_chr']):
        cnv_chr = int(row['VS_Call_chr'][3:])
        cnv_start = int(row['VS_Call_start'])
        cnv_end = int(row['VS_Call_end'])
        
        if cnv_chr != int(row['chr'][3:]):
            return 0
        else:
            overlap_percentage = calculate_within_window_percentage(row['start'], 
                                                                    row['end'], cnv_start, cnv_end, denominator)
            return overlap_percentage
    else:
        return np.nan

# Apply the function with the specified denominator
VarSeq_results_df['VarSeq_overlap_within_window_based_on_call_length'] = VarSeq_results_df.apply(
    lambda row: output_overlapping_and_within_window_percentage(row, "call length"), axis=1
)

VarSeq_results_df['VarSeq_overlap_within_window_based_on_window_length'] = VarSeq_results_df.apply(
    lambda row: output_overlapping_and_within_window_percentage(row, "window length"), axis=1
)

## Storing per sample RECALLED CNV calls for each sample-simulated CNV pair
### A ClinVar CNV is considered recalled if there is a CNV called that overlaps the ClinVar CNV coordinates (overlap > 0).
### We will have a separate table 'recalled_cnvs_not_all_exons_called' for recalled CNVs that do not have all exons within CNV that are detected

In [20]:
# Function to count simulated exons within the VS-called coordinates
def counting_sim_exons_within_VS_call(VS_chr, VS_start, VS_end, sim_chr, sim_start, sim_end, exons):
    # Check if any of the inputs are NaN; if so, return 0 as the count
    if pd.isna(VS_chr) or pd.isna(VS_start) or pd.isna(VS_end) or pd.isna(sim_chr) or pd.isna(sim_start) or pd.isna(sim_end):
        return 0
    
    # Ensure VS_chr and sim_chr are strings and coordinates are integers
    VS_chr = str(VS_chr)
    VS_start = int(VS_start)
    VS_end = int(VS_end)
    sim_chr = str(sim_chr)
    sim_start = int(sim_start)
    sim_end = int(sim_end)
    
    # Filter exons within simulated chromosome and coordinates
    exons_on_sim_chr = exons[(exons['chr'] == sim_chr) & (exons['start'] >= sim_start) & (exons['end'] <= sim_end)]
    
    # From the filtered exons, count how many are fully contained within VS_start and VS_end
    # +1 adjustment for 
    count = sum((exons_on_sim_chr['start']+1 >= VS_start) & (exons_on_sim_chr['end'] <= VS_end))
    return count

# Function to count all exons within the VS-called coordinates
def counting_all_exons_overlapping_VS_call(VS_chr, VS_start, VS_end, exons):
    # Check if any of the inputs are NaN; if so, return 0 as the count
    if pd.isna(VS_chr) or pd.isna(VS_start) or pd.isna(VS_end):
        return 0
    
    # Ensure VS_chr and sim_chr are strings and coordinates are integers
    VS_chr = str(VS_chr)
    VS_start = int(VS_start)
    VS_end = int(VS_end)
    
    # Filter exons within simulated chromosome and coordinates
    exons_on_VS_chr = exons[(exons['chr'] == VS_chr) & (exons['start']+1 >= VS_start) & (exons['end'] <= VS_end)]
    
    # From the filtered exons, count how many are fully contained within VS_start and VS_end
    # +1 adjustment for 
    count = len(exons_on_VS_chr)
    return count


# Function to calculate percentage of total length of all exons that are within
# and/or partially overlapping with the ClinVar CNV coordinate
def calculate_exon_overlap_percentage(row, exons_df):
    # Filter exons on the same chromosome and within or overlapping the CNV coordinates
    overlapping_exons = exons_df[
        (exons_df['chr'] == row['chr']) &
        (exons_df['end'] >= row['start']) &
        (exons_df['start'] <= row['end'])
    ]

    total_overlap_length = 0
    total_exon_length = 0

    for _, exon in overlapping_exons.iterrows():
        # Calculate overlap
        overlap_start = max(row['start'], exon['start'])
        overlap_end = min(row['end'], exon['end'])
        overlap_length = max(0, overlap_end - overlap_start)

        # Add overlap length and exon length
        total_overlap_length += overlap_length
        total_exon_length += exon['end'] - exon['start']

    # Calculate overlap percentage
    if total_exon_length > 0:
        overlap_percentage = (total_overlap_length / total_exon_length) * 100
    else:
        overlap_percentage = 0

    return (total_overlap_length, overlap_percentage)

# Modified check_recalled function with pre-filtered exons
def check_recalled(row):
    estimated_cn = row['Estimated CN of CNV']
    cn = row['cn']
    VS_chr = row['VS_Call_chr']
    VS_start = row['VS_Call_start']
    VS_end = row['VS_Call_end']
    sim_chr = row['chr']
    sim_start = row['start']
    sim_end = row['end']
    count_exons_overlapping_simulated_window = row['count_exons_overlapping_simulated_window']
    count_exons_within_simulated_window = row['count_exons_within_simulated_window']
    overlap = row['VarSeq_overlap_within_window_based_on_window_length']

    # Count exons within the VS-called region based on pre-filtered simulated region
    count_sim_exons_within_VS_call = counting_sim_exons_within_VS_call(VS_chr, VS_start, VS_end, sim_chr, sim_start, sim_end, exons)
    count_all_exons_overlapping_VS_call = counting_all_exons_overlapping_VS_call(VS_chr, VS_start, VS_end, exons)
    
    # Define valid CN matches
    valid_cn_match = estimated_cn == cn or (estimated_cn, cn) in [(3, 4), (4, 3)]

    # Check recall conditions
    if cn != 2 and count_exons_overlapping_simulated_window > 0:
        if overlap > 0 and valid_cn_match:
            return (True, count_sim_exons_within_VS_call, count_all_exons_overlapping_VS_call)
        # if count_exons_within_simulated_window <= 1 and overlap > 0 and valid_cn_match:
        #     return (True, count_sim_exons_within_VS_call)
        # elif count_exons_within_simulated_window > 1 and count_sim_exons_within_VS_call > 0 and valid_cn_match:
        #     return (True, count_sim_exons_within_VS_call)

    return (False, count_sim_exons_within_VS_call, count_all_exons_overlapping_VS_call)

# Apply the function to each row and split the output into two separate columns
VarSeq_results_df[['recalled', 'count_sim_exons_within_VS_call', 'count_all_exons_overlapping_simulated_window']] = \
VarSeq_results_df.apply(lambda row: check_recalled(row), axis=1).apply(pd.Series)

VarSeq_results_df[['exon_overlap_length', 'exon_overlap_percentage']] = \
VarSeq_results_df.apply(lambda row: calculate_exon_overlap_percentage(row , exons_df=exons), axis=1).apply(pd.Series)

# # Apply calculate_exon_overlap_percentage functions
# unique_false_rows['exon_overlap_percentage'] = unique_false_rows.apply(
#     calculate_exon_overlap_percentage, exons_df=exons, axis=1
# )


# recalled['exon_overlap_percentage'] = recalled.apply(
#     calculate_overlap_percentage, exons_df=exons, axis=1
# )

In [21]:
len(VarSeq_results_df)

670

## Parse the 'Precision Level of call:' column to separate the comma-separated values.

In [22]:
VarSeq_results_df['Precision Level of call:'] = VarSeq_results_df['Precision Level of call:'].str.strip()

# Define the precision levels with a regular expression
precision_levels = {
    'Very High Sensitivity': r"\(1\) Very High Sensitivity",
    'High Sensitivity': r"\(2\) High Sensitivity",
    'Balanced': r"\(3\) Balanced",
    'High Precision': r"\(4\) High Precision",
    'Very High Precision': r"\(5\) Very High Precision"
}

# Create new columns with True/False based on presence of each precision level
for level_name, pattern in precision_levels.items():
    VarSeq_results_df[level_name] = VarSeq_results_df['Precision Level of call:'].str.contains(pattern)

## Extracting the false positives first

In [23]:
false_positives_varseq = VarSeq_results_df[VarSeq_results_df['VarSeq_overlap_within_window_based_on_window_length'] == 0]

In [24]:
print('number of false positives: ' + str(len(false_positives_varseq)))

number of false positives: 30

In [25]:
false_positives_varseq.to_csv(varseq_tables_path + '/false_positives_varseq.csv')

## Filtering out the five duplicate ClinVar deletions that i accidentally left in the simulations

In [26]:
# Identify groups where 'chr', 'start', 'end', 'gene', 'cn' have multiple unique 'sample' values
duplicated_groups = VarSeq_results_df.groupby(['chr', 'start', 'end', 'gene', 'cn'])['sample'].nunique()
filtered_keys = duplicated_groups[duplicated_groups > 1].index

# Split the dataframe into duplicates and non-duplicates
duplicates = VarSeq_results_df[VarSeq_results_df.set_index(['chr', 'start', 'end', 'gene', 'cn']).index.isin(filtered_keys)]
non_duplicates = VarSeq_results_df[~VarSeq_results_df.set_index(['chr', 'start', 'end', 'gene', 'cn']).index.isin(filtered_keys)]

# For duplicates, keep only the row where recalled == True, if it exists
duplicates = duplicates.sort_values(by=['recalled'], ascending=False).drop_duplicates(subset=['chr', 'start', 'end', 'gene', 'cn'], keep='first')

# Combine back the filtered duplicates with the original non-duplicates
VarSeq_results_df = pd.concat([non_duplicates, duplicates]).reset_index(drop=True)

In [27]:
duplicates

,cn,sample,chr,start,end,gene,count_exons_overlapping_simulated_window,count_exons_within_simulated_window,summed_length_exons_overlapping,summed_length_exons_within,...,recalled,count_sim_exons_within_VS_call,count_all_exons_overlapping_simulated_window,exon_overlap_length,exon_overlap_percentage,Very High Sensitivity,High Sensitivity,Balanced,High Precision,Very High Precision
348,1,cn1_DNS-XTHS-0106-C05-DNS009868_S131_chr17_430...,chr17,43047704,43051062,BRCA1,3,1,340,124,...,True,1,3,173.0,50.882353,True,True,True,True,True
395,1,cn1_DNS-XTHS-0106-E01-DNS009838_S101_chr17_430...,chr17,43067608,43067695,BRCA1,1,0,138,0,...,True,0,1,87.0,63.043478,True,True,True,True,True
411,1,cn1_DNS-XTHS-0106-E12-DNS009926_S189_chr17_430...,chr17,43076488,43076614,BRCA1,1,0,177,0,...,True,0,1,126.0,71.186441,True,True,True,True,True
455,1,cn1_DNS-XTHS-0105-H11-DNS009825_S88_chr17_4311...,chr17,43115726,43115779,BRCA1,1,0,104,0,...,True,0,1,53.0,50.961538,True,True,True,True,True
460,1,cn1_DNS-XTHS-0107-D06-DNS009973_S236_chr16_236...,chr16,23603162,23603669,PALB2,1,0,261,0,...,True,0,1,236.0,90.421456,True,True,False,False,False

## Printing out overall simulation results

In [28]:
# Print out number of CNVs not covered by panel bed file
print("Number of CNVs not covered by Panel BED file: ", len(VarSeq_results_df[VarSeq_results_df['count_exons_overlapping_simulated_window'] == 0]))

# Filter out rows where CNVs are not covered by the exon bed file:
VarSeq_results_df = VarSeq_results_df[VarSeq_results_df['count_exons_overlapping_simulated_window'] != 0]

Number of CNVs not covered by Panel BED file:  0

In [29]:
# Step 1: Group by the combination of 'sample', 'chr', 'start', 'end' and check if any of them have 'recalled' == True
grouped = VarSeq_results_df.groupby(['cn', 'sample', 'chr', 'start', 'end'])['recalled'].any().reset_index()

# Step 2: Filter out combinations where 'recalled' == True is present in the group
only_true_combinations = grouped[grouped['recalled'] == True][['cn', 'sample', 'chr', 'start', 'end']]

In [30]:
print('number of recalled CNVs: ' + str(len(only_true_combinations)))

number of recalled CNVs: 578

In [31]:
recalled_del = only_true_combinations[only_true_combinations['cn'] == 1]
print('number of recalled deletions: ' + str(len(recalled_del)))

number of recalled deletions: 504

In [32]:
recalled_dup = only_true_combinations[only_true_combinations['cn'] == 3]
print('number of recalled duplications: ' + str(len(recalled_dup)))

number of recalled duplications: 74

In [33]:
for level in precision_levels:
    df_slice = VarSeq_results_df[(VarSeq_results_df[level] == True) & (VarSeq_results_df['recalled'] == True)]
    df_slice_grouped = df_slice.groupby(['sample', 'cn', 'chr', 'start', 'end']).any().reset_index()
    
    print(f"Number of CNV calls recalled with {level}: {len(df_slice_grouped)}")
    break

Number of CNV calls recalled with Very High Sensitivity: 578

## Below is a CNV that is NOT called at Very High Sensitivity but called at lower sensitivity settings...

In [34]:
# Find rows in only_true_combinations where 'sample' is not in df_slice
diff = only_true_combinations[~only_true_combinations['sample'].isin(df_slice['sample'])]

print(diff)

Empty DataFrame
Columns: [cn, sample, chr, start, end]
Index: []

In [35]:
for level in precision_levels:
    df_slice = VarSeq_results_df[(VarSeq_results_df[level] == True) & (VarSeq_results_df['recalled'] == True)]
    df_slice_grouped = df_slice.groupby(['cn', 'sample', 'chr', 'start', 'end']).any().reset_index()
    
    print(f"Number of CNV calls recalled with {level}: {len(df_slice_grouped)}")

Number of CNV calls recalled with Very High Sensitivity: 578
Number of CNV calls recalled with High Sensitivity: 550
Number of CNV calls recalled with Balanced: 494
Number of CNV calls recalled with High Precision: 479
Number of CNV calls recalled with Very High Precision: 465

Note that some simulated CNVs have multiple calls made at different precision levels. The calls just have different coordinates (longer/shorter compared to the others).

If a call is made at multiple precision levels, the call made at 'higher' precision is usually more accurate to the intended regions that i simulate compared to the 'higher' sensitivity one.

In [36]:
VarSeq_results_df.to_csv(sim_dir + '/run' + dnascreen_run + '/plot_generation/Full_VS_CNV_Calls_metrics' + sensitivity + '.csv')

## Filtering out some CNV calls that are duplicate (simulated on the same region and sample) but got extra exons called
## also collapsing the duplicate calls to the call made at the higher precision.
## because i can't have duplicate CNV calls for the same simulation cause i'm feeding them to the R scripts for volcano plots

In [37]:
# VarSeq_results_df = VarSeq_results_df.sort_values(
#     by=['sample', 'recalled', 'Precision Level of call:'], 
#     ascending=[True, False, False]  # Sort 'Precision Level of call:' in descending order
# )

# VarSeq_results_df = VarSeq_results_df.drop_duplicates(subset=['sample', 'cn'], keep='first')

# VarSeq_results_df = VarSeq_results_df.reset_index(drop=True)

In [38]:
# Step 1: Filter rows where 'recalled' == True
filtered_df = VarSeq_results_df[VarSeq_results_df['recalled'] == True].copy()

# Step 2: Define a function to determine the best CNV per sample
def choose_best_cnv(group):
    # First, prioritize rows where 'Number of Exons by VarSeq call' >= 'count_exons_overlapping_simulated_window'
    group['exon_difference'] = group['Number of Exons by VarSeq call'] - group['count_exons_overlapping_simulated_window']
    
    # Prioritize CNVs where exon_difference is >= 0
    best_cnv = group[group['exon_difference'] >= 0]
    
    if not best_cnv.empty:
        # If multiple CNVs qualify, select the one with the smallest exon_difference
        return best_cnv.loc[best_cnv['exon_difference'].idxmin()]
    
    # If no CNVs qualify, choose the one with the smallest absolute exon_difference
    return group.loc[group['exon_difference'].abs().idxmin()]

# Step 3: Apply the function group-wise based on the 'sample' column
filtered_df = filtered_df.groupby('sample', group_keys=False).apply(choose_best_cnv)

# Step 4: Drop the temporary 'exon_difference' column
filtered_df = filtered_df.drop(columns=['exon_difference'])

# Result: DataFrame with only the best CNV per sample
filtered_df

,cn,sample,chr,start,end,gene,count_exons_overlapping_simulated_window,count_exons_within_simulated_window,summed_length_exons_overlapping,summed_length_exons_within,...,recalled,count_sim_exons_within_VS_call,count_all_exons_overlapping_simulated_window,exon_overlap_length,exon_overlap_percentage,Very High Sensitivity,High Sensitivity,Balanced,High Precision,Very High Precision
sample,,,,,,,,,,,,,,,,,,,,,
cn1_DNS-XTHS-0105-A01-DNS009738_S1_chr17_43124017_43124115.sorted,1,cn1_DNS-XTHS-0105-A01-DNS009738_S1_chr17_43124...,chr17,43124017,43124115,BRCA1,1,0,130,0,...,True,0,1,98.0,75.384615,True,True,True,True,True
cn1_DNS-XTHS-0105-A01-DNS009738_S1_chr2_47403295_47407170.sorted,1,cn1_DNS-XTHS-0105-A01-DNS009738_S1_chr2_474032...,chr2,47403295,47407170,MSH2,1,0,261,0,...,True,0,1,132.0,50.574713,True,True,False,False,False
cn1_DNS-XTHS-0105-A02-DNS009746_S9_chr17_43045677_43049120.sorted,1,cn1_DNS-XTHS-0105-A02-DNS009746_S9_chr17_43045...,chr17,43045677,43049120,BRCA1,3,1,410,111,...,True,1,3,286.0,69.756098,True,True,False,False,False
cn1_DNS-XTHS-0105-A02-DNS009746_S9_chr19_11100222_11107515.sorted,1,cn1_DNS-XTHS-0105-A02-DNS009746_S9_chr19_11100...,chr19,11100222,11107515,LDLR,5,3,1123,777,...,True,3,5,1074.0,95.636687,False,True,True,True,True
cn1_DNS-XTHS-0105-A03-DNS009754_S17_chr17_43102513_43107537.sorted,1,cn1_DNS-XTHS-0105-A03-DNS009754_S17_chr17_4310...,chr17,43102513,43107537,BRCA1,3,3,457,457,...,True,3,3,457.0,100.000000,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cn3_DNS-XTHS-0107-G06-DNS010250_S239_chr3_37011814_37042337.sorted,3,cn3_DNS-XTHS-0107-G06-DNS010250_S239_chr3_3701...,chr3,37011814,37042337,MLH1,9,7,1636,1429,...,True,7,9,1597.0,97.616137,True,True,True,True,True
cn3_DNS-XTHS-0107-G08-DNS009992_S255_chr19_11116092_11116999.sorted,3,cn3_DNS-XTHS-0107-G08-DNS009992_S255_chr19_111...,chr19,11116092,11116999,LDLR,2,0,359,0,...,True,0,2,311.0,86.629526,True,True,True,True,False
cn3_DNS-XTHS-0107-G10-DNS010008_S271_chr17_43099070_43102393.sorted,3,cn3_DNS-XTHS-0107-G10-DNS010008_S271_chr17_430...,chr17,43099070,43102393,BRCA1,1,1,156,156,...,True,1,1,156.0,100.000000,True,True,True,True,True
cn3_DNS-XTHS-0107-H11-DNS010017_S280_chr17_43047298_43054952.sorted,3,cn3_DNS-XTHS-0107-H11-DNS010017_S280_chr17_430...,chr17,43047298,43054952,BRCA1,3,3,340,340,...,True,3,3,340.0,100.000000,True,True,True,True,True
cn3_DNS-XTHS-0107-H12-DNS010025_S288_chr17_43076615_43090943.sorted,3,cn3_DNS-XTHS-0107-H12-DNS010025_S288_chr17_430...,chr17,43076615,43090943,BRCA1,3,1,538,222,...,True,1,3,271.0,50.371747,True,True,True,True,True

In [39]:
len(filtered_df) == len(only_true_combinations)

True

In [40]:
recalled = filtered_df

## NOTE THAT THE Recalled_VS_CNV_Calls_metrics contains calls with highest precision only.

In [41]:
recalled.to_csv(sim_dir + '/run' + dnascreen_run + '/plot_generation/Recalled_VS_CNV_Calls_metrics' + sensitivity + '.csv')

## Recalled CNVs that do not have all exons within CNV that are detected

## Good to have this as a sanity check. NOTE: One CNV in Run 33 have one less exon within CNV that is not detected as part of the CNV

In [42]:
recalled_cnvs_not_all_exons_called = \
filtered_df[(filtered_df['recalled'] == True) & (filtered_df['count_exons_within_simulated_window'] > filtered_df['count_sim_exons_within_VS_call'])]

In [43]:
print('number of recalled CNVs that do not have all exons within CNV detected: ' + str(len(recalled_cnvs_not_all_exons_called)))

number of recalled CNVs that do not have all exons within CNV detected: 0

In [44]:
recalled_cnvs_not_all_exons_called.to_csv(sim_dir + '/run' + dnascreen_run + '/plot_generation/recalled_cnvs_not_all_exons_called.csv')

## Listing down missed CNVs by VarSeq

In [45]:
# Step 1: Group by the combination of 'sample', 'chr', 'start', 'end' and check if any of them have 'recalled' == True
grouped = VarSeq_results_df.groupby(['cn', 'sample', 'chr', 'start', 'end'])['recalled'].any().reset_index()

# Step 2: Filter out combinations where 'recalled' == True is present in the group
only_false_combinations = grouped[(grouped['recalled'] == False) & (grouped['cn'] != 2)][['cn', 'sample', 'chr', 'start', 'end']]

# Step 3: Merge back with the original DataFrame to get only rows with 'recalled' == False
unique_false_rows = VarSeq_results_df.merge(only_false_combinations, on=['cn', 'sample', 'chr', 'start', 'end'])
unique_false_rows = unique_false_rows[unique_false_rows['recalled'] == False]

In [46]:
print('number of missed CNVs: ' + str(len(only_false_combinations)))

number of missed CNVs: 43

In [47]:
missed_del = only_false_combinations[only_false_combinations['cn'] == 1]
print('number of missed deletions: ' + str(len(missed_del)))
print('number of recalled deletions: ' + str(533 - len(missed_del)))

number of missed deletions: 29
number of recalled deletions: 504

In [48]:
missed_dup = only_false_combinations[only_false_combinations['cn'] == 3]
print('number of missed duplications: ' + str(len(missed_dup)))
print('number of recalled duplications: ' + str(88 - len(missed_dup)))

number of missed duplications: 14
number of recalled duplications: 74

In [49]:
unique_false_rows.to_csv(varseq_tables_path + '/missed_cnvs_with_varseq_calls.csv')

In [50]:
# For easy exporting as a table to be presented
unique_false_rows[['cn', 'chr', 'start', 'end', 'gene', 'summed_length_exons_overlapping', \
                   'Percent Difference', 'Read Ratio of Simulated CNV', 'Read Ratio of Original CNV region', 'Z-Score of Simulated CNV', 'Z-Score of Original CNV region', \
                   'Target Mean Depth of Original CNV region', 'Target Mean Depth of Simulated CNV']].to_csv(varseq_tables_path + '/notion_missed_cnvs_with_varseq_calls.csv')

## Extracting all Z-Scores of non-overlapping exons to plot mean and std error bars in Z-Score vs CN plot later

In [51]:
# # Create a list to store the flattened Z-scores and their corresponding CN
# z_scores_flattened = []
# cn_values = []

# for cn, z_scores in enumerate(avg_z_scores_all_nonmatching_sim_exons):
#     z_scores_flattened.extend(z_scores)
#     cn_values.extend([cn] * len(z_scores))

# # Create a DataFrame from the flattened list
# z_scores_per_cn_nonmatching_sim_exons = pd.DataFrame({
#     'z_score_varseq': z_scores_flattened,
#     'cn': cn_values
# })

In [52]:
# z_scores_per_cn_nonmatching_sim_exons.to_csv(sim_dir + '/run' + dnascreen_run + '/plot_generation/z_scores_per_cn_nonmatching_exons.csv')

## Storing per sample CNV calls for Exome Depth
## Merge rows with calls split between 10 runs into a single row. Separate the metrics from the different calls by comma in some columns

In [53]:
# # Importing Exome Depth calls
# df_ED_CNV = pd.read_csv(sim_dir + '/run' + dnascreen_run + '/plot_generation/exome_depth_stats_different_ref_samples.csv')

In [54]:
# # Define the columns to concatenate
# columns_to_concat = [
#     'Frequency', 'ED_length', 'ED_chr', 'ED_start', 'ED_end', 'ED_percentage_within_window',
#     'Mean_Reads_Expected', 'Mean_Reads_Observed', 'Mean_Reads_Ratio', 'Mean_BF', 'Mean_Correlation'
# ]

# # Function to concatenate values for the specified columns
# def concatenate_values(group):
#     concatenated_values = {col: ', '.join(group[col].astype(str)) for col in columns_to_concat}
#     return pd.Series(concatenated_values)

In [55]:
# # Group by 'sample' and apply the concatenation function
# merged_df_ED_CNV = df_ED_CNV.groupby('sample').apply(concatenate_values).reset_index()

# # Drop duplicate rows and merge with concatenated values
# df_ED_CNV = df_ED_CNV.drop(columns=columns_to_concat).drop_duplicates(subset='sample')
# df_ED_CNV_final = pd.merge(df_ED_CNV, merged_df_ED_CNV, on='sample')

In [56]:
# df_ED_CNV_final

In [57]:
# merged_df = varseq_results_df_final.merge(df_ED_CNV_final, left_on=['sample', 'chr', 'start', 'end'], right_on=['sample', 'sim_chr', 'sim_start', 'sim_end'])

In [58]:
# # clean up the table by removing unecessary columns
# columns_to_drop = ['overlap_with_start_chr', 'overlap_with_start_start', 
#                    'overlap_with_start_end', 'overlap_with_start_name', 
#                    'overlap_with_end_chr', 'overlap_with_end_start', 
#                    'overlap_with_end_end', 'overlap_with_end_name',
#                    'call_key', 'sim_chr', 'sim_start', 
#                    'sim_end', 'sim_length', 'cn_ED'
#                   ]

# merged_df.drop(columns=columns_to_drop, inplace=True)

In [59]:
# merged_df.to_csv(sim_dir + '/run' + dnascreen_run + '/plot_generation/VS_ED_CNV_Calls_metrics.csv')